// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: person.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Woman_Level int32

const (
	Woman_STUDENT   Woman_Level = 0
	Woman_FURNACE   Woman_Level = 1
	Woman_CONCUBINE Woman_Level = 2
	Woman_WIFE      Woman_Level = 3
)

var Woman_Level_name = map[int32]string{
	0: "STUDENT",
	1: "FURNACE",
	2: "CONCUBINE",
	3: "WIFE",
}

var Woman_Level_value = map[string]int32{
	"STUDENT":   0,
	"FURNACE":   1,
	"CONCUBINE": 2,
	"WIFE":      3,
}

func (x Woman_Level) String() string {
	return proto.EnumName(Woman_Level_name, int32(x))
}

func (Woman_Level) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{2, 0}
}

type PersonListRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonListRequest) Reset()         { *m = PersonListRequest{} }
func (m *PersonListRequest) String() string { return proto.CompactTextString(m) }
func (*PersonListRequest) ProtoMessage()    {}
func (*PersonListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}
func (m *PersonListRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PersonListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PersonListRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PersonListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonListRequest.Merge(m, src)
}
func (m *PersonListRequest) XXX_Size() int {
	return m.Size()
}
func (m *PersonListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PersonListRequest proto.InternalMessageInfo

func (m *PersonListRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PersonListRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type PersonListResponse struct {
	Women                []*Woman `protobuf:"bytes,1,rep,name=women,proto3" json:"women,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonListResponse) Reset()         { *m = PersonListResponse{} }
func (m *PersonListResponse) String() string { return proto.CompactTextString(m) }
func (*PersonListResponse) ProtoMessage()    {}
func (*PersonListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{1}
}
func (m *PersonListResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PersonListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PersonListResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PersonListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonListResponse.Merge(m, src)
}
func (m *PersonListResponse) XXX_Size() int {
	return m.Size()
}
func (m *PersonListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PersonListResponse proto.InternalMessageInfo

func (m *PersonListResponse) GetWomen() []*Woman {
	if m != nil {
		return m.Women
	}
	return nil
}

func (m *PersonListResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Woman struct {
	Id                   int32       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32       `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Level                Woman_Level `protobuf:"varint,4,opt,name=level,proto3,enum=rpc.Woman_Level" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Woman) Reset()         { *m = Woman{} }
func (m *Woman) String() string { return proto.CompactTextString(m) }
func (*Woman) ProtoMessage()    {}
func (*Woman) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{2}
}
func (m *Woman) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Woman) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Woman.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Woman) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Woman.Merge(m, src)
}
func (m *Woman) XXX_Size() int {
	return m.Size()
}
func (m *Woman) XXX_DiscardUnknown() {
	xxx_messageInfo_Woman.DiscardUnknown(m)
}

var xxx_messageInfo_Woman proto.InternalMessageInfo

func (m *Woman) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Woman) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Woman) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Woman) GetLevel() Woman_Level {
	if m != nil {
		return m.Level
	}
	return Woman_STUDENT
}

func init() {
	proto.RegisterEnum("rpc.Woman_Level", Woman_Level_name, Woman_Level_value)
	proto.RegisterType((*PersonListRequest)(nil), "rpc.PersonListRequest")
	proto.RegisterType((*PersonListResponse)(nil), "rpc.PersonListResponse")
	proto.RegisterType((*Woman)(nil), "rpc.Woman")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d) }

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0x4d, 0x4b, 0xc3, 0x30,
	0x18, 0x5e, 0xd2, 0x65, 0xba, 0x77, 0x3a, 0xe2, 0xcb, 0xd0, 0xe2, 0xa1, 0x94, 0x1e, 0xa4, 0xa7,
	0x1e, 0xe6, 0x49, 0x2f, 0xe2, 0x66, 0x07, 0x83, 0x51, 0x25, 0x6e, 0x0c, 0xbc, 0xed, 0x23, 0xc8,
	0x60, 0x4b, 0x62, 0xdb, 0xe9, 0x5f, 0xf1, 0xea, 0xbf, 0xf1, 0xe8, 0x4f, 0x90, 0xf9, 0x47, 0x64,
	0xa9, 0x6c, 0x42, 0x6f, 0xef, 0xf3, 0xbc, 0x49, 0x9e, 0x8f, 0xc0, 0x91, 0x91, 0x69, 0xa6, 0x55,
	0x64, 0x52, 0x9d, 0x6b, 0x74, 0x52, 0x33, 0x0b, 0xae, 0xe0, 0xe4, 0xc1, 0x92, 0x83, 0x45, 0x96,
	0x0b, 0xf9, 0xb2, 0x96, 0x59, 0x8e, 0x08, 0x55, 0x35, 0x59, 0x49, 0x97, 0xf8, 0x24, 0xac, 0x0b,
	0x3b, 0x23, 0x07, 0x67, 0xf2, 0x2c, 0x5d, 0xea, 0x93, 0x90, 0x89, 0xed, 0x18, 0x0c, 0x00, 0xff,
	0x5f, 0xcd, 0x8c, 0x56, 0x99, 0x44, 0x1f, 0xd8, 0x9b, 0x5e, 0x49, 0xe5, 0x12, 0xdf, 0x09, 0x1b,
	0x6d, 0x88, 0x52, 0x33, 0x8b, 0xc6, 0x7a, 0x35, 0x51, 0xa2, 0x58, 0x60, 0x0b, 0xd8, 0x4c, 0xaf,
	0x55, 0xfe, 0xf7, 0x56, 0x01, 0x82, 0x0f, 0x02, 0xcc, 0x1e, 0xc3, 0x26, 0xd0, 0xc5, 0xdc, 0x6a,
	0x33, 0x41, 0x17, 0xf3, 0x9d, 0x1b, 0x5a, 0x76, 0xe3, 0xec, 0xdc, 0xe0, 0x05, 0xb0, 0xa5, 0x7c,
	0x95, 0x4b, 0xb7, 0xea, 0x93, 0xb0, 0xd9, 0xe6, 0x7b, 0xdd, 0x68, 0xb0, 0xe5, 0x45, 0xb1, 0x0e,
	0xae, 0x81, 0x59, 0x8c, 0x0d, 0x38, 0x78, 0x1c, 0x8e, 0xee, 0xe2, 0x64, 0xc8, 0x2b, 0x5b, 0xd0,
	0x1b, 0x89, 0xe4, 0xb6, 0x1b, 0x73, 0x82, 0xc7, 0x50, 0xef, 0xde, 0x27, 0xdd, 0x51, 0xa7, 0x9f,
	0xc4, 0x9c, 0xe2, 0x21, 0x54, 0xc7, 0xfd, 0x5e, 0xcc, 0x9d, 0x76, 0x1f, 0x6a, 0x45, 0x62, 0xbc,
	0x01, 0xd8, 0x67, 0xc7, 0x53, 0x2b, 0x56, 0xea, 0xf1, 0xfc, 0xac, 0xc4, 0x17, 0x25, 0x05, 0x95,
	0x4e, 0xeb, 0x73, 0xe3, 0x91, 0xaf, 0x8d, 0x47, 0xbe, 0x37, 0x1e, 0x79, 0xff, 0xf1, 0x2a, 0x4f,
	0xd4, 0x4c, 0xa7, 0x35, 0xfb, 0x33, 0x97, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3b, 0xcd, 0xbb,
	0x9a, 0xa9, 0x01, 0x00, 0x00,
}

func (m *PersonListRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PersonListRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PersonListRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Age != 0 {
		i = encodeVarintPerson(dAtA, i, uint64(m.Age))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintPerson(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PersonListResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PersonListResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PersonListResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Count != 0 {
		i = encodeVarintPerson(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Women) > 0 {
		for iNdEx := len(m.Women) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Women[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPerson(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Woman) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Woman) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Woman) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Level != 0 {
		i = encodeVarintPerson(dAtA, i, uint64(m.Level))
		i--
		dAtA[i] = 0x20
	}
	if m.Age != 0 {
		i = encodeVarintPerson(dAtA, i, uint64(m.Age))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintPerson(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintPerson(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintPerson(dAtA []byte, offset int, v uint64) int {
	offset -= sovPerson(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PersonListRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovPerson(uint64(l))
	}
	if m.Age != 0 {
		n += 1 + sovPerson(uint64(m.Age))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *PersonListResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Women) > 0 {
		for _, e := range m.Women {
			l = e.Size()
			n += 1 + l + sovPerson(uint64(l))
		}
	}
	if m.Count != 0 {
		n += 1 + sovPerson(uint64(m.Count))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Woman) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovPerson(uint64(m.Id))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovPerson(uint64(l))
	}
	if m.Age != 0 {
		n += 1 + sovPerson(uint64(m.Age))
	}
	if m.Level != 0 {
		n += 1 + sovPerson(uint64(m.Level))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovPerson(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPerson(x uint64) (n int) {
	return sovPerson(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PersonListRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPerson
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PersonListRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PersonListRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPerson
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPerson
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPerson
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Age", wireType)
			}
			m.Age = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPerson
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Age |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPerson(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPerson
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PersonListResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPerson
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PersonListResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PersonListResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Women", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPerson
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPerson
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPerson
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Women = append(m.Women, &Woman{})
			if err := m.Women[len(m.Women)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPerson
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPerson(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPerson
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Woman) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPerson
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Woman: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Woman: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPerson
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPerson
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPerson
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPerson
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Age", wireType)
			}
			m.Age = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPerson
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Age |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Level", wireType)
			}
			m.Level = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPerson
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Level |= Woman_Level(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPerson(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPerson
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPerson(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPerson
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPerson
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPerson
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPerson
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPerson
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPerson
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPerson        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPerson          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPerson = fmt.Errorf("proto: unexpected end of group")
)
